version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 60
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 60
